---
grsec_sysctl_flags:
  - name: "kernel.grsecurity.rwxmap_logging"
    value: "0"
    # The grsec lock value needs to be the last sysctl flag set or else the
    # rest will not be applied
  - name: "kernel.grsecurity.grsec_lock"
    value: "1"

