---
  # The authd ossec process automatically adds the app server ossec agent it is
  # not an authenticated process. There is an option we could add to create and
  # verify the server/agents ssl keys with the root CA cert. see
  # http://ossec-docs.readthedocs.org/en/latest/programs/ossec-authd.html
- name: check to see if app agent already exists
  shell: /var/ossec/bin/list_agents -a
  register: list_agents

- name: create authd SSL keys
  shell: creates=/var/ossec/etc/sslmanager.key openssl genrsa -out /var/ossec/etc/sslmanager.key 4096
  when: list_agents != "{{ app_hostname }}-{{ app_ip }} is available."

- name: create ssl cert
  shell: creates=/var/ossec/etc/sslmanager.cert openssl req -new -x509 -batch -subj "/CA=AU/ST=Some-State/locality=city/O=Internet Widgits Pty Ltd/commonName=mon/organizationUnitName=section/emailAddress=admin@localhost" -key /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert -days 365
  when: list_agents != "{{ app_hostname }}-{{ app_ip }} is available."

- stat: path=/etc/network/iptables/rules_v4
  register: iptables_rules
  when: list_agents.stdout != "{{ app_hostname }}-{{ app_ip }} is available."

- name: add firewall rule exmeption for authd
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    insertafter: "^:LOGNDROP"
    regexp: "{{ item }}"
    line: "{{ item }}"
  notify:
    - reload iptables rules
  with_items: authd_rules
  when: iptables_rules.stat.exists and list_agents.stdout != "{{ app_hostname }}-{{ app_ip }} is available."

- name: start authd
  shell: "/var/ossec/bin/ossec-authd -i {{ app_ip }} -p 1515 >/dev/null 2>&1 &"
  async: 0
  poll: 0
  when: list_agents.stdout != "{{ app_hostname }}-{{ app_ip }} is available."
