---
- name: install tor project apt signing gpg key
  apt_key: >
    state=present
    data="{{ lookup('file', 'tor-signing-key.pub') }}"

- name: setup tor apt repo
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ tor_distribution_release }} main'
    state=present 
    update_cache=yes

## in case {{ tor_distribution_release }} is a development branch (ie. the name starts with tor-experimental), the line with the distribution name is also needed to install deb.torproject.org-keyring
- name: get distribution name from tor_distribution_release variable
  shell: python -c "print '{{ tor_distribution_release }}'.split('-')[-1]"
  register: distribution
  when: tor_distribution_release.startswith('tor-experimental')

- name: setup tor apt repo in case tor_distribution_release is a development branch
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ distribution.stdout }} main'
    state=present 
    update_cache=yes
  when: tor_distribution_release.startswith('tor-experimental')

- name: install tor and tor keyring packages
  apt:
    pkg: "{{ item }}"
    state: latest
    force: yes
  with_items: ["deb.torproject.org-keyring", "tor"]

- name: template torrc
  template: src=torrc dest=/etc/tor/torrc
    owner=root group=root mode=0644
  notify:
  - restart tor

- name: ensure tor is running
  service: name=tor state=running
