---
  # The ubuntu motd include displaying some system load averages.
  # this causes a grsec: From 10.0.2.2: denied RWX mmap of <anonymous mapping>
  # by /usr/bin/landscape-sysinfo[landscape-sysin:3393] uid/euid:0/0
  # gid/egid:0/0, parent
  # /usr/share/landscape/landscape-sysinfo.wrapper[50-landscape-sy:3386]
  # uid/euid:0/0 gid/egid:0/0
  # Disabling calling that script during login.
- name: remove motd pam module from ssh logins
  lineinfile: dest=/etc/pam.d/sshd regexp=pam.motd state=absent backup=yes

- name: install grsec predepends paxctl package
  apt: pkg=paxctl state=present

- name: make the required grub paxctl changes
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax

- name: install grsec package from fpf repo
  apt: pkg={{ grsec_package }} state=latest
  async: 200
  poll: 10
