---
  # The ubuntu motd include displaying some system load averages.
  # this causes a grsec: From 10.0.2.2: denied RWX mmap of <anonymous mapping>
  # by /usr/bin/landscape-sysinfo[landscape-sysin:3393] uid/euid:0/0
  # gid/egid:0/0, parent
  # /usr/share/landscape/landscape-sysinfo.wrapper[50-landscape-sy:3386]
  # uid/euid:0/0 gid/egid:0/0
  # Disabling calling that script during login.
- name: remove motd pam module from ssh logins
  lineinfile: dest=/etc/pam.d/sshd regexp=pam.motd state=absent backup=yes

- name: install grsec predepends paxctl package
  apt: pkg=paxctl state=present

- name: make the required grub paxctl changes
  command: paxctl -Cpm {{ item }}
  with_items: grub_pax

- name: install grsec package from fpf repo
  apt: pkg={{ grsec_package }} state=latest
  async: 300
  poll: 10

- name: get grsec kernel string
  shell: grep menuentry /boot/grub/grub.cfg | grep grsec | grep -v recovery | head -1 | cut -d "'" -f2
  register: grsec_str

- name: set grsec kernel as default for next boot
  command: grub-reboot "Advanced options for Ubuntu>{{ grsec_str.stdout }}"

- stat: path=/var/run/grsec-installed
  register: grsec_installed

- name: reboot into the grsec kernel
  command: shutdown -r now "Rebooting into the grsec kernel..."
  async: 0
  poll: 0
  ignore_errors: true
  when: grsec_installed.stat.exists
  when: not grsec_lock.stat.exists
  tags:
    - reboot

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port={{ ansible_ssh_port }}
      delay=45
      state=started
  sudo: false
  tags:
    - reboot

- name: remove generic kernel metapackages
  apt: name=linux-signed-image-generic-lts-utopic state=absent
  apt: name=linux-signed-image-generic state=absent
  apt: name=linux-signed-generic-lts-utopic state=absent
  apt: name=linux-signed-generic state=absent

- name: remove remaining generic kernels
  command: apt-get -y remove '^linux-image-.*generic$'

- name: remove remaining kernel headers
  command: apt-get -y remove '^linux-headers-.*'

- name: cleanup any dependencies left
  command: apt-get -y autoremove
