---
- name: install tor project apt signing gpg key
  apt_key: >
    state=present
    data="{{ lookup('file', 'tor-signing-key.pub') }}"

- name: setup tor apt repo
  apt_repository: >
    repo='deb http://deb.torproject.org/torproject.org {{ distribution_release }} main'
    state=present 
    update_cache=yes

- name: install tor and tor keyring packages
  apt:
    pkg: "{{ item }}"
    state: latest
    force: yes
  with_items: ["deb.torproject.org-keyring", "tor"]
