---
securedrop_kernel_packages_to_remove:
  - linux-virtual
  - linux-generic
  - 'linux-image-.*generic'

resolvconf_target_filepath: /etc/resolv.conf

securedrop_common_packages:
  - apt-transport-https
  - iptables-persistent
  - unattended-upgrades
  - tmux
