---
- name: Begin registration process for {{ signal_number }}.
  command: /usr/local/bin/signal-cli -u {{ signal_number }} register
  args:
    creates:
      - "~{{ ansible_user }}/.config/signal/data/{{ signal_number }}"
  register: signal_registration_result

- name: Begin re-registration process for {{ signal_number }}.
  command: /usr/local/bin/signal-cli -u {{ signal_number }} register
  when: signal_registration_result|skipped and signal_force_re_registration

- block:
  - name: Prompt for Signal confirmation code.
    pause:
      prompt: "Please enter the Signal confirmation code you just received:"
    register: signal_registration_prompt

  - name: Verify Signal confirmation code and complete registration.
    command: /usr/local/bin/signal-cli -u {{ signal_number }} verify {{ signal_registration_prompt.user_input }}

  when: ansible_interactive_mode and (signal_registration_result|changed or signal_force_re_registration)

- name: Provide instructions on completing the registration process when run in non-interactive mode.
  debug:
    msg: "I've begun the Signal registration process with phone number {{ signal_number }} for you. Since Ansible was not running in interactive mode when this role was run, I couldn't pause to prompt you for your verification code. To complete the registration process run the command `ansible -m command -a \"/usr/local/bin/signal-cli -u {{ signal_number }} verify <verification code>\"` against the target host."
  when: (not ansible_interactive_mode) and (signal_registration_result|changed or signal_force_re_registration)
