---
- name: ensure /var/www/html/ is removed
  file:
    state: absent
    dest: "/var/www/html"

- name: ensure securedrop root directory exists
  file:
    state: directory
    mode: 0700
    owner: www-data
    group: www-data
    dest: "{{ securedrop_root }}"

- name: ensure securedrop data directory exists 
  file:
    state: directory
    mode: 0700
    owner: www-data
    group: www-data
    dest: "{{ securedrop_data }}"

- name: ensure securedrop data store directory exists
  file:
    state: directory
    mode: 0700
    owner: www-data
    group: www-data
    dest: "{{ securedrop_data }}/store"

- name: ensure securedrop keyring directory exists
  file:
    state: directory
    mode: 0700
    owner: www-data
    group: www-data
    dest: "{{ securedrop_data }}/keys"
