---
# Whether to set the Apache AppArmor profiles to "complain".
# Can aid in debugging the AppArmor profiles, but also permits
# misconfigurations, and so should be used with caution.
securedrop_app_test_apparmor_complain: False

# Username for Apache service, used to set permissions on the
# Source Interface config to enable logging in the staging environment.
apache_user: www-data

# Additional apt packages required for running the application tests.
test_apt_dependencies:
  - enchant
  - firefox
  - gettext
  - xvfb

# Additional Python dependencies required for running the application tests.
test_pip_requirements: "{{ securedrop_code }}/requirements/test-requirements.txt"
