---
- name: Install pip dependencies for running the unit and functional tests.
  pip:
    requirements: "{{ test_pip_requirements }}"
  tags:
    - pip

- name: Install testing package dependencies.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: test_apt_dependencies
  tags:
    - apt

# Selenium 3 makes breaking changes with the 2.X API, and requires the
# installation of the Mozilla geckodriver. Since the Aaron Swartz Day Hackathon
# is approaching, which will involve many new external contributors, we've
# decided to play it as safe as possible by downgrading Firefox to the latest
# version (46.0.1) that is compatible with the last 2.X series Selenium release
# (2.53.6). After the Hackathon, we'll resolve the geckodriver business and
# remove the following three tasks (as well as add firefox back to the
# `test_apt_dependencies` list).
- name: Download Firefox 46.0.1 for compatibility with Selenium 2.53.6.
  sudo: no
  get_url:
    # Since the whole tasklisk is run as root, the ansible_env.HOME fact is
    # /root. Since this command doesn't need to be run as root and is part of a
    # crutch anyway, I've just hardcoded /home/vagrant.
    dest: /home/vagrant/
    url: https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/+build/9727836/+files/firefox_46.0.1+build1-0ubuntu0.14.04.3_amd64.deb
    sha256sum: 88d25053306d33658580973b063cd459a56e3596a3a298c1fb8ab1d52171d860
  tags:
    - apt

- name: Install dependencies for Firefox 46.0.1.
  apt:
    name: "{{ item }}"
  with_items:
    - libasound2
    - libcairo-gobject2
    - libgtk-3-0
    - libstartup-notification0
  tags:
    - apt

- name: Install Firefox 46.0.1 for compatibility with Selenium 2.53.6.
  apt:
    deb: /home/vagrant/firefox_46.0.1+build1-0ubuntu0.14.04.3_amd64.deb
  tags:
    - apt

- name: Copy xvfb init script.
  copy:
    src: xvfb
    dest: /etc/init.d/xvfb
    owner: root
    mode: '700'
  tags:
    - xvfb
    - permissions

- name: Update rc.d to run xvfb at boot.
  command: update-rc.d xvfb defaults
  register: xvfb_setup
  changed_when: "'System start/stop links for /etc/init.d/xvfb already exist' not in xvfb_setup.stdout"
  notify: start xvfb
  tags:
    - xvfb

- name: Set DISPLAY environment variable for xvfb.
  copy:
    src: xvfb_display.sh
    dest: /etc/profile.d/xvfb_display.sh
    owner: root
    mode: '444'
  tags:
    - xvfb
    - environment
    - permissions
