---
  # Since production environment does not have dhcp or dns create etc hosts
  # entries
- include: set_etc_hosts_for_prod_env.yml
  tags:
      # CI environment uses a vps where we use vagrant-hostmanger to manage
      # /etc/hosts
    - static-hosts

- include: app_configure_tor_hidden_services.yml

- include: app_display_onions.yml
