---
- name: ensure /etc/hosts file has entry for app and monitor servers
  lineinfile:
    backup: yes
    dest: /etc/hosts
    insertafter: EOF
    line: "{{ item.ip }}  {{ item.hostname }}"
    regexp: "^{{ item.ip }}    {{ item.hostname }}"
  with_items: ip_info
