---
- name: Install OSSEC manager package.
  apt:
    name: securedrop-ossec-server
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt

- name: Install procmail.
  apt:
    name: procmail
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
    - procmail

- name: Copy the OSSEC GPG public key for sending encrypted alerts.
  copy:
    src: "{{ ossec_alert_gpg_public_key }}"
    dest: /var/ossec
  tags:
    - gpg

- name: Add the OSSEC GPG public key to the OSSEC manager keyring.
  # multiline format for command module, since this is a long command
  command: >
    su -s /bin/bash -c 'gpg
    --homedir /var/ossec/.gnupg
    --import /var/ossec/{{ ossec_alert_gpg_public_key }}' {{ ossec_group }}
  register: add_ossec_gpg_key_result
  changed_when: "'imported: 1' in add_ossec_gpg_key_result.stderr"
  tags:
    - gpg

- name: Copy script for sending GPG-encrypted OSSEC alerts.
  template:
    src: send_encrypted_alarm.sh
    dest: /var/ossec/send_encrypted_alarm.sh
    mode: 775
    owner: ossec
    group: root
  tags:
    - procmail
    - permissions

  # This log file doesn't exist by default, so we need to create it. We don't
  # want to clobber the contents if it already exists, however, thus the "force: no".
  # The `copy` module will back off if the file already exists, which means permissions
  # will be ignored if the file exists. A subsequent task will handle permissions.
- name: Create procmail log file.
  copy:
    dest: /var/log/procmail.log
    mode: "0660"
    owner: ossec
    group: root
    content: ""
    force: no
  tags:
    - procmail
    - permissions
    - logging

  # The previous task is essentially a `touch` command, without the side-effect of reporting
  # "changed" every time. In order to force correct ownership and permissions, we'll take a
  # second pass at the log file and only report "changed" if updates were made.
- name: Update permissions on procmail log file.
  file:
    path: /var/log/procmail.log
    mode: "0660"
    owner: ossec
    group: root
  tags:
    - procmail
    - permissions
    - logging

- name: Copy procmail config file.
  copy:
    src: procmailrc
    dest: /var/ossec/.procmailrc
    owner: ossec
    group: root
  tags:
    - procmail
