---
# Directory for storing the DEBIAN control files.
securedrop_app_code_deb_dir: "/tmp/{{ securedrop_app_code_deb }}"

# Directory for storing the filtered application code files. These files
# are "filtered" via an `.rsync-filter` file in the src directory.
securedrop_code_filtered: "{{ securedrop_app_code_deb_dir }}/var/www/securedrop"

securedrop_pip_requirements: "{{ securedrop_code_filtered }}/requirements/securedrop-app-code-requirements.txt"

securedrop_app_rsync_opts:
  - "--chmod=u=rwX,g=rX,o=rX"
  - "--chown=root:root"
  - "--exclude=*.git"
  - "--exclude=*aths"
  - "--exclude=*.deb"

securedrop_local_build: "../../build"

# Whether to build packages targeting Xenial. Some of the dependency
# logic changes, so we'll adjust the control file accordingly.
securedrop_build_xenial_support: False
securedrop_package_dist: "{{ 'xenial' if securedrop_build_xenial_support else 'trusty' }}"
