
# cargo-vet audits file

[[audits.ascii-canvas]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "3.0.0"

[[audits.bitflags]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "1.3.2"

[[audits.cc]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
delta = "1.0.73 -> 1.0.83"

[[audits.chrono]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.4.26 -> 0.4.31"

[[audits.crc32fast]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "1.3.2"

[[audits.diff]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.1.13"

[[audits.digest]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.9.0"

[[audits.dirs-next]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "2.0.0"

[[audits.dirs-sys-next]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.1.2"

[[audits.ena]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.14.2"

[[audits.fixedbitset]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.4.2"

[[audits.generic-array]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.14.6"

[[audits.getrandom]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.1.16"

[[audits.getrandom]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
delta = "0.1.16 -> 0.2.6"

[[audits.iana-time-zone]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.1.58"
notes = "Only code for Linux was reviewed."

[[audits.idna]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.3.0 -> 0.4.0"
notes = "Primarily adding a no_std mode"

[[audits.lalrpop]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.19.10 -> 0.20.0"
notes = "Autogenerated code was not reviewed."

[[audits.lalrpop-util]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.19.12"

[[audits.lalrpop-util]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.19.12 -> 0.20.0"

[[audits.memoffset]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.6.5"

[[audits.memsec]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.6.3"

[[audits.petgraph]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.6.2 -> 0.6.4"

[[audits.phf_shared]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.10.0"

[[audits.pkg-config]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.3.26 -> 0.3.27"

[[audits.ppv-lite86]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.2.10 -> 0.2.16"

[[audits.pyo3]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.18.3"

[[audits.pyo3-build-config]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.18.3"
notes = "Windows, cross-compiling and abi3 code not reviewed."

[[audits.pyo3-ffi]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.18.3"
notes = "Unsurprisingly lots of unsafe, appears fine for an FFI library. PyPy and Windows code was skipped."

[[audits.pyo3-macros]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.18.3"

[[audits.pyo3-macros-backend]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.18.3"

[[audits.rand]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.7.3 -> 0.8.5"

[[audits.rand]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "0.8.3 -> 0.8.5"

[[audits.rand_chacha]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
delta = "0.2.2 -> 0.3.1"

[[audits.rand_core]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
delta = "0.5.1 -> 0.6.3"

[[audits.siphasher]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "0.3.10"

[[audits.smallvec]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
delta = "1.6.1 -> 1.11.1"

[[audits.string_cache]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.8.7"

[[audits.term]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.7.0"
notes = "Windows code was not reviewed."

[[audits.tiny-keccak]]
who = "Cory Francis Myers <cory@freedom.press>"
criteria = "safe-to-run"
version = "2.0.2"

[[audits.typenum]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "1.15.0"

[[audits.xxhash-rust]]
who = "Kunal Mehta <legoktm@debian.org>"
criteria = "safe-to-run"
version = "0.8.7"
notes = "Only the `xxh3` feature, used by Sequoia, was reviewed"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.buffered-reader]]
criteria = "safe-to-deploy"
user-id = 33886 # Neal H. Walfield (nwalfield)
start = "2023-01-06"
end = "2024-04-10"
notes = "Sequoia developer"

[[trusted.bzip2]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-07-06"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.bzip2-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-02-24"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-01"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.dyn-clone]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-12-23"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.either]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2019-04-02"
end = "2024-04-10"

[[trusted.ena]]
criteria = "safe-to-deploy"
user-id = 1386 # Niko Matsakis (nikomatsakis)
start = "2019-03-19"
end = "2024-05-02"
notes = "Rust Project member"

[[trusted.equivalent]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2023-02-05"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.errno]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2023-08-29"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.flate2]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-14"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2020-01-15"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.indoc]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-28"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.lalrpop]]
criteria = "safe-to-deploy"
user-id = 1386 # Niko Matsakis (nikomatsakis)
start = "2023-03-25"
end = "2024-05-02"
notes = "Rust Project member"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-29"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2021-01-27"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.lock_api]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.num-traits]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2019-05-20"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.openssl]]
criteria = "safe-to-deploy"
user-id = 5
start = "2019-02-22"
end = "2024-05-02"
notes = "Rust Project member"

[[trusted.openssl]]
criteria = "safe-to-deploy"
user-id = 163 # Alex Gaynor (alex)
start = "2023-03-24"
end = "2024-05-02"
notes = "Rust Project member"

[[trusted.openssl-sys]]
criteria = "safe-to-deploy"
user-id = 5
start = "2019-03-01"
end = "2024-05-02"
notes = "Rust Project member"

[[trusted.openssl-sys]]
criteria = "safe-to-deploy"
user-id = 163 # Alex Gaynor (alex)
start = "2023-03-24"
end = "2024-05-29"
notes = "Rust Project member"

[[trusted.parking_lot]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.parking_lot_core]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.scopeguard]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.sequoia-openpgp]]
criteria = "safe-to-deploy"
user-id = 33886 # Neal H. Walfield (nwalfield)
start = "2022-11-18"
end = "2024-04-10"
notes = "Sequoia developer"

[[trusted.sequoia-openpgp]]
criteria = "safe-to-deploy"
user-id = 33711 # Justus Winter (teythoon)
start = "2019-03-14"
end = "2024-12-12"
notes = "Sequoia developer"

[[trusted.sha1collisiondetection]]
criteria = "safe-to-deploy"
user-id = 33886 # Neal H. Walfield (nwalfield)
start = "2022-08-28"
end = "2024-04-10"
notes = "Sequoia developer"

[[trusted.sha1collisiondetection]]
criteria = "safe-to-deploy"
user-id = 14969
start = "2023-05-05"
end = "2024-04-10"
notes = "Sequoia developer"

[[trusted.sha1collisiondetection]]
criteria = "safe-to-deploy"
user-id = 33711 # Justus Winter (teythoon)
start = "2020-11-11"
end = "2024-04-27"
notes = "Sequoia developer"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.target-lexicon]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2019-03-06"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2024-04-10"
notes = "Rust Project member"

[[trusted.unindent]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-08-17"
end = "2024-04-10"
notes = "Rust Project member"
