---
## Tor
tor_instance_parent_dir: /etc/tor/instances
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
tor_PidFile: /var/run/tor/tor.pid
tor_RunAsDaemon: 1
tor_Log: "notice file /var/log/tor/log"
tor_hidden_services_parent_dir: /var/lib/tor/services
tor_wait_for_hidden_services: no

## Interface defaults
securedrop_root: "/var/www/securedrop"
securedrop_data: "/var/lib/securedrop"
securedrop_user: "www-data"

apache_user: "www-data"

apache_packages:
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile

apache_files:
  - 'apache2.conf'
  - 'security'

apache_templates:
  - 'ports.conf'
  - 'sites-available/document.conf'
  - 'sites-available/source.conf'

apache_modules:
  - access_compat
  - authn_core
  - alias
  - authz_core
  - authz_host
  - authz_user
  - deflate
  - filter
  - dir
  - headers
  - mime
  - mpm_event
  - negotiation
  - reqtimeout
  - rewrite
  - wsgi
  - xsendfile

## TODO instead of hard coding disabled modules find intersection of
#apache_modules vs enabled modules
apache_disabled_modules:
  - auth_basic
  - authn_file
  - autoindex
  - env
  - setenvif
  - status

apache_sites:
  - source
  - document

app_deps:
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apparmor-utils

dev_deps:
  - libssl-dev
  - python-dev
  - python-pip
  - firefox
  - xvfb

build_deb_root:
  - /tmp/securedrop-debs

# Build FPF deb packages
build_deb_dirs:
  - securedrop-app-code
  - securedrop-python-mods
  - ossec-agent
  - ossec-server
  - securedrop-ossec-agent
  - securedrop-ossec-server

## System Hardening
apparmor_profiles:
  - usr.bin.tor
  - usr.lib.apache2.mpm-worker.apache2

distro_id: "ubuntu"
distro_codename: "trusty"
ossec_group: "ossec"
ossec_config_path: "{{ ossec_root }}/etc/ossec.conf"
ossec_package_name: "ossec-agent"
