---
- name: Remove default Apache site directory /var/www/html/.
  file:
    state: absent
    dest: "/var/www/html"
  tags:
    - apache
    - permissions

- name: Create SecureDrop app code directory.
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_code }}"
  tags:
    - permissions

- name: Create SecureDrop data directory.
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}"
  tags:
    - permissions

- name: Create SecureDrop data store directory.
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/store"
  tags:
    - permissions

- name: Create SecureDrop keyring directory.
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/keys"
  tags:
    - permissions

- name: Create SecureDrop temp directory.
  file:
    state: directory
    mode: 0700
    owner: "{{ securedrop_user }}"
    group: "{{ securedrop_user }}"
    dest: "{{ securedrop_data }}/tmp"
  tags:
    - permissions
