---
- name: Install apache packages.
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: apache_packages
  tags:
    - apt
    - apache

- name: Copy Apache configuration and security files.
  copy:
    src: "{{ item }}"
    dest: /etc/apache2/{{ item }}
    owner: root
    mode: '0644'
  with_items: apache_files
  tags:
    - apache

- name: Copy Apache ports and site configs.
  template:
    src: "{{ item }}"
    dest: /etc/apache2/{{ item }}
    owner: root
    mode: '0644'
  with_items: apache_templates
  tags:
    - apache

- name: Enable required Apache modules.
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items: apache_modules
  tags:
    - apache

- name: Disable blacklisted Apache modules.
  apache2_module:
    state: absent
    name: "{{ item }}"
  with_items: apache_disabled_modules
  tags:
    - apache
    - hardening

- name: Disable default Apache sites.
  file:
    state: absent
    dest: /etc/apache2/sites-enabled/{{ item }}
  with_items:
    - 000-default.conf
    - default-ssl.conf
    - default.conf
  tags:
    - apache
    - hardening

- name: Enable SecureDrop Apache sites.
  file:
    state: link
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item }}.conf"
  with_items:
    - document
    - source
  notify:
    - restart apache2
  tags:
    - apache
