---
galaxy_info:
  author: David Stainton
  description: Ansible Tor role
  license: license MIT
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
  - networking
  min_ansible_version: 1.3
dependencies: []
