---
# This role will upgrade 0.3pre instances to 0.3 instances.
# It will copy and run the upgrade.py script on the app and monitor servers.
- name: stop the apache service prior to upgrade tasks
  service: name=apache2 state=stopped
  when: server_role == 'app'
  sudo: yes

- name: copy upgrade script to servers
  copy: src="0.3pre_upgrade.py" dest="/tmp" owner="root" mode="740"
  sudo: yes

- name: run the upgrade script
  shell: "/tmp/0.3pre_upgrade.py {{ server_role }}"
  sudo: yes

- name: remove old 0.3 packages to avoid version error
  apt: name={{ item }} state=absent
  with_items:
    - securedrop-app-code
    - securedrop-grsec
    - securedrop-ossec-agent
    - securedrop-ossec-server
  sudo: yes

- name: remove the previous signing key
  apt_key: id=BD67D096 state=absent
  sudo: yes

  # This will update the App servers torrc config file for changing the
  # journalist interface tor port from 8080 to 80. As of this release the prod
  # playbook restarts tor if the torrc config changes. This will break ansible
  # playbook runs that are over tor. Issue #940 will track modifying the prod
  # playbook to ensure that this isn't an issue going forward.
  #
  # This does not change the ATHS onion address or secret value only the port
  # for the interface will change.
  #
  # This will only replace/add the line when the old HiddenServicePort config
  # for port 8080 exists. This will not modify the torrc on the monitor server
  # which only has a HiddenServicePort 22 config.
- name: change the journalist interface ATHS virtual port to lisen on port 80
  lineinfile:
    dest: /etc/tor/torrc
    regexp: '^HiddenServicePort 8080 127\.0\.0\.1\:8080'
    backrefs: yes
    line: 'HiddenServicePort 80 127.0.0.1:8080'
  notify: reload tor for port change
  sudo: yes

  # If the config changed, reload tor now instead of after all the remaining
  # upgrade tasks are run so the next task can verify
  # that the service is running.
- meta: flush_handlers

- name: ensure tor is running
  service: name=tor state=running
  sudo: yes
