---
# Set the default SSH listening address for the sshd config file.
# In production, sshd listening to localhost (127.0.0.1), since all SSH
# connections are forced over Tor. In staging, this value will be 0.0.0.0
# to enable direct access for testing during development.
ssh_listening_address: 127.0.0.1

enable_ssh_over_tor: false

# This var is defined in the tor-hidden-services role, but won't be available
# in separate plays, so declaring it within the context of iptables role, so
# the hostname files can be fetched back to the Admin Workstation.
tor_hidden_services_parent_dir: /var/lib/tor/services
