---
# This will look for packages in install_files/ansible-base,
# so the "build" directory is relative to playbook, which is
# why the parent dirs ("..") are necessary.
- name: if defined copy local deb packages to target system
  copy:
    src: ../../build/{{ item }}
    dest: /root/
  with_items: local_deb_packages
  tags:
    - install_local_pkgs

# There's a known bug in Ansible that causes installing
# .deb packages via the apt module to fail when invoked
# with `with_items`. A temporary workaround is to use
# `with_indexed_items` and reference the value, which tricks
# the `apt` module into installing each deb package separately,
# rather than joining into a single comma-separated string.
- name: if defined install local deb packages
  apt:
    deb: /root/{{ item.1 }}
  with_indexed_items: local_deb_packages
  tags:
    - install_local_pkgs
