---
- name: Install securedrop-ossec-agent package.
  apt:
    name: securedrop-ossec-agent
    state: present
  tags:
    - apt

  # Check for the IPv4 rules file on disk. On the first run of this playbook,
  # the file won't exist yet. Only add iptables rules if the file already exists.
- name: Check whether iptables rules exist.
  stat:
    path: /etc/network/iptables/rules_v4
  register: iptables_rules_check_result

- name: Add firewall exemption for OSSEC agent registration.
  lineinfile:
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    insertafter: "^:LOGNDROP"
    regexp: "{{ item }}"
    line: "{{ item }}"
  notify: reload iptables rules
  with_items: agent_auth_rules
  when: hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and
        iptables_rules_check_result.stat.exists == true
  tags:
    - iptables
    - ossec_auth

- name: Register OSSEC agent.
  command: /var/ossec/bin/agent-auth -m {{ monitor_ip }} -p 1515 -A {{ app_hostname }}
  when: hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false
  tags:
    - ossec_auth

  # If the OSSEC agent auth iptable rule exemptions are in place remove them and
  # restart OSSEC. This order does matter. The app server's
  # ossec agent needs to restart to load the imported cert from authd and
  # connect to the ossec server. The monitor server's OSSEC server needs to
  # restart after the agent connects to correctly display the agent status.
- name: Remove firewall exemption for OSSEC agent registration.
  lineinfile:
    state: absent
    dest: /etc/network/iptables/rules_v4
    line: "{{ item }}"
  register: removed_ossec_exemptions
  notify:
    - reload iptables rules
    - restart ossec
  with_items: agent_auth_rules
  when: hostvars[groups.securedrop_monitor_server.0].ossec_agent_already_registered == false and
        iptables_rules_check_result.stat.exists == true
  tags:
    - iptables
    - ossec_auth

