---
- hosts: [ 'build' ]

  vars:
    ossec_server_hostname: ossec-server
    version: "2.8.2"
    download_url: "https://github.com/ossec/ossec-hids/archive"
    download_name: "{{ version }}.tar.gz"
    archive_name: "ossec-hids-{{ download_name }}"
    build_path: "/vagrant/build"
    arch: "amd64"
    ossec_build_dir: "ossec-{{ purpose }}-{{ version }}-{{ arch }}"
    build_ossec_deb_pkg_dependencies:
      - inotify-tools
      - libssl-dev
      - make
      - tar
      - unzip

  roles:
    - { role: build-ossec-deb-pkg, tags: [ "ossec-server" ], purpose: "server" }
    - { role: build-ossec-deb-pkg, tags: [ "ossec-agent" ], purpose: "agent" }

  sudo: yes
