---

- name: ensure tor instance parent dir exists
  file: >
    path={{ tor_instance_parent_dir }}
    state=directory
    owner={{ tor_user }}

- name: ensure tor instances data dir exist
  file: >
    path="{{ tor_instance_parent_dir }}/{{ item.name }}/data"
    state=directory
    owner={{ tor_user }}
  with_items: proc_instances

- name: ensure tor instances log file exist
  file: >
    path="{{ tor_instance_parent_dir }}/{{ item.name }}/log"
    state=touch
    owner={{ tor_user }}
  with_items: proc_instances

- name: ensure tor instances pid file exist
  file: >
    path="{{ tor_instance_parent_dir }}/{{ item.name }}/tor.pid"
    state=touch
    owner={{ tor_user }}
  with_items: proc_instances

- name: ensure instances template torrc
  template: >
    src=torrc
    dest="{{ tor_instance_parent_dir }}/{{ item.name }}/torrc"
    owner={{ tor_user }}
    mode=0644
  with_items: proc_instances
  register: instances_status

- name: ensure tor instances are reloaded if it's torrc changed
  shell: "kill -HUP `cat {{ tor_instance_parent_dir }}/{{ item.item.name }}/tor.pid`"
  ignore_errors: yes
  with_items: instances_status.results
  when: item.changed == True

- name: ensure tor instances are running
  shell: "pgrep `cat {{ tor_instance_parent_dir }}/{{ item.name }}/tor.pid` || tor -f {{ tor_instance_parent_dir }}/{{ item.name }}/torrc"
  with_items: proc_instances
