---
  # This needs to be run after seting the etc hosts or else will get a hostname
  # error change these to lineinfile module to work with the exemptions
- include: mon_iptables.yml

- include: mon_configure_tor_hidden_services.yml

- include: mon_display_onions.yml

- include: mon_install_fpf_deb_pkgs.yml

  # authd will go here

- include: mon_configure_ossec_gpg_alerts.yml

- include: mon_install_postfix.yml
