---
- name: Update apt package lists.
  apt:
      update_cache: yes
  tags:
    - apt
    - development

- name: Install apt package dependencies for Development environment.
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ development_dependencies }}"
  tags:
    - apt
    - development

- name: Install pip dependencies for SecureDrop.
  pip:
    requirements: "{{ securedrop_pip_requirements }}"
  tags:
    - pip
    - development

- name: Install sass Ruby gem
  gem:
    name: sass
    state: latest
    user_install: no
  sudo: yes
  tags:
    - development

# necessary for automated tests
- name: Compile sass to css
  shell: >
    if [ -d /home/travis ]; then
      /home/travis/.rvm/bin/rvm install 2.3.0 &&
      /home/travis/.rvm/bin/rvm use 2.3.0 &&
      gem install sass &&
      $(find /home/travis/.rvm -name sass | grep /wrappers/sass | head -1) --update sass:static/css
    else 
      sass --update sass:static/css
    fi
  args:
    chdir: '{{ securedrop_repo  }}/securedrop'
  tags:
    - development

# Setting at the system-wide level to apply to all users.
- name: Set SECUREDROP_ENV in bashrc.
  copy:
    dest: /etc/profile.d/securedrop_env.sh
    content: "export SECUREDROP_ENV=dev"
  tags:
    - environment
    - development
