---
#securedop_repo is defined in site-specific.yml config

### Used by the common role ###
# ssh_users is defined in the site-specific.yml config
# app_ip is defined in the site-specific.yml config
# app_hostname is defined in the site-specific.yml config

# For setting the etc hosts entries
ip_info:
  - ip: "{{ app_ip }}"
    hostname: "{{ app_hostname }}"

# Installing securedrop-ossec-server.deb package
#
# This is the path to the directory where we build the deb. The deb package
# will be created alongside it and will have ".deb" automatically appended.
securedrop_ossec_server_deb: "{{ securedrop_repo }}/securedrop-ossec-server-2.8.2-amd64"


### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - ossec-server-2.8.2-amd64.deb
  - "securedrop-ossec-server-2.8.2+{{ securedrop_app_code_version }}-amd64.deb"

### Used by the mon role ###

# Configure the tor hidden services. The Monitor server has only one,
# for SSH, since no web interfaces.
tor_instances:
  - service: ssh
    filename: mon-ssh-aths

# Packages to install from fpf repo
mon_fpf_packages:
  - securedrop-ossec-server

# Apt dependencies for the ossec server package
ossec_postfix_dependencies:
  - procmail
  - postfix
  - mailutils

# Configuration info for procmail and postfix
postfix_hostname: ossec.server
#ossec_alert_gpg_public_key_public_key_path is defined in the site-specific.yml config
#ossec_gpg_fpr is defined in the site-specific.yml config
#ossec_alert_email is defined in the site-specific.yml config
#smtp_relay is defined in the site-specific.yml config
#smtp_relay_port is defined in the site-specific.yml config
#smtp_relay_fingerprint is defined in the site-specific.yml config
#sasl_username is defined in the site-specific.yml config
#sasl_domain is defined in the site-specific.yml config
#sasl_password is defined in the site-specific.yml config

authd_rules:
  - "-A INPUT -s {{ app_hostname }} -p tcp --dport 1515 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -d {{ app_hostname }} -p tcp --sport 1515 -m state --state ESTABLISHED,RELATED -j ACCEPT"

### Used by the test role ###

# To allow direct access
direct_access_rules:
  - "-A INPUT -i {{ansible_default_ipv4.interface}} -p tcp --dport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -o {{ansible_default_ipv4.interface}} -p tcp --sport 22 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A OUTPUT -p udp --dport 53 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A INPUT -p udp --sport 53 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
