---
# For setting the etc hosts entries
ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"

### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - "securedrop-keyring-0.1.4+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
  - "securedrop-config-0.1.4+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
  - "securedrop-ossec-agent-3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}-amd64.deb"
  -  securedrop-grsec-{{ grsec_version }}+{{ securedrop_target_distribution }}-amd64.deb
  - "{{ securedrop_app_code_deb }}.deb"
  - "ossec-agent-3.6.0+{{ securedrop_target_distribution }}-amd64.deb"

# Configuring the tor onion services
tor_instances:
  - "{{ {'service': 'ssh', 'filename': 'app-ssh-aths'} if enable_ssh_over_tor else [] }}"
  - service: source
    filename: app-source-ths
  - service: journalist
    filename: app-journalist-aths

tor_instances_v3:
  - "{{ {'service': 'sshv3', 'filename': 'app-ssh.auth_private'} if enable_ssh_over_tor else [] }}"
  - service: sourcev3
    filename: app-sourcev3-ths
  - service: journalistv3
    filename: app-journalist.auth_private

tor_auth_instances_v3:
  - "{{ 'sshv3' if enable_ssh_over_tor  else [] }}"
  - "journalistv3"

authd_iprules:
  - chain: OUTPUT
    dest: "{{ monitor_ip  }}"
    proto: tcp
    dest_port: 1515
    match: state
    cstate: "NEW,ESTABLISHED,RELATED"
    jump: ACCEPT

  - chain: INPUT
    source: "{{ monitor_ip  }}"
    proto: tcp
    source_port: 1515
    match: state
    cstate: "ESTABLISHED,RELATED"
    jump: ACCEPT

# Declare Application Server as OSSEC agent role.
ossec_is_client: yes

ssh_ip: "{{ app_ip|default(ansible_default_ipv4.address) }}"
adjacent_sd_ip: "{{ monitor_ip }}"
