---
# Variables that apply to both the app and monitor server go in this file
# If the monitor or app server need different values define the variable in 
# hosts_vars/app.yml or host_vars/mon.yml host_vars/development.yml
tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor
tor_DataDirectory: /var/lib/tor
securedrop_tor_user: "debian-tor"

disabled_kernel_modules:
  - bluetooth
  - iwlwifi

ssh_2fa_dependencies:
  - libpam-google-authenticator

sysctl_flags:
  - name: "net.ipv4.tcp_max_syn_backlog"
    value: "4096"
  - name: "net.ipv4.tcp_syncookies"
    value: "1"
  - name: "net.ipv4.conf.all.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.all.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.all.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.all.secure_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.default.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.default.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.secure_redirects"
    value: "0"
  - name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: "1"
  - name: "net.ipv4.ip_forward"
    value: "0"
  - name: "net.ipv4.conf.all.send_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.send_redirects"
    value: "0"
  - name: "net.ipv6.conf.all.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.default.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.lo.disable_ipv6"
    value: "1"

# grsec vars
grub_pax:
  - /usr/sbin/grub-probe
  - /usr/sbin/grub-mkdevicemap

grsec_package: securedrop-grsec

### Used by the build-ossec-deb-pkg roles ###
build_ossec_deb_pkg_dependencies:
  - inotify-tools
  - libssl-dev
  - make
  - tar
  - unzip
ossec_group: "ossec"
ossec_download_url: "http://www.ossec.net/files/ossec-hids-2.8.1.tar.gz"
ossec_download_checksum: "03c073761aa484fe21a9fcc0ea318ba132ff2466c64360408046a4b8e527b529"
ossec_download_md5: "c2ffd25180f760e366ab16eeb82ae382"
ossec_version: "ossec-hids-2.8.1"
ossec_archive: "{{ securedrop_repo }}/build/{{ ossec_version }}.tar.gz"
ossec_deb_path: "{{ securedrop_repo }}/build"
