---
# For setting the etc hosts entries
ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"

### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - "securedrop-keyring-0.1.2+{{ securedrop_app_code_version }}-amd64.deb"
  - "securedrop-config-0.1.2+{{ securedrop_app_code_version }}-amd64.deb"
  - "securedrop-ossec-agent-3.0.0+{{ securedrop_app_code_version }}-amd64.deb"
  - "{{ securedrop_app_code_deb }}.deb"
  - "ossec-agent-3.0.0-amd64.deb"

# Configuring the tor hidden services
tor_instances:
  - "{{ {'service': 'ssh', 'filename': 'app-ssh-aths'} if enable_ssh_over_tor else [] }}"
  - service: source
    filename: app-source-ths
  - service: journalist
    filename: app-journalist-aths

authd_iprules:
  - chain: OUTPUT
    dest: "{{ monitor_ip  }}"
    proto: tcp
    dest_port: 1515
    match: state
    cstate: "NEW,ESTABLISHED,RELATED"
    jump: ACCEPT

  - chain: INPUT
    source: "{{ monitor_ip  }}"
    proto: tcp
    source_port: 1515
    match: state
    cstate: "ESTABLISHED,RELATED"
    jump: ACCEPT

# Declare Application Server as OSSEC agent role.
ossec_is_client: yes

ssh_ip: "{{ app_ip|default(ansible_default_ipv4.address) }}"
adjacent_sd_ip: "{{ monitor_ip }}"
