---
# For setting the etc hosts entries
ip_info:
  - ip: "{{ app_ip }}"
    hostname: "{{ app_hostname }}"

### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - "securedrop-keyring-0.1.2+{{ securedrop_app_code_version }}-amd64.deb"
  - "securedrop-config-0.1.3+{{ securedrop_app_code_version }}-amd64.deb"
  - "securedrop-ossec-server-3.0.0+{{ securedrop_app_code_version }}-amd64.deb"
  - ossec-server-3.0.0-amd64.deb

# Configure the tor hidden services. The Monitor server has only one,
# for SSH, since no web interfaces.
tor_instances: "{{ [{ 'service': 'ssh', 'filename': 'mon-ssh-aths'}] if enable_ssh_over_tor else [] }}"

authd_iprules:
  - chain: INPUT
    source: "{{ app_hostname  }}"
    proto: tcp
    dest_port: 1515
    match: state
    cstate: "NEW,ESTABLISHED,RELATED"
    jump: ACCEPT

  - chain: OUTPUT
    dest: "{{ app_hostname }}"
    proto: tcp
    source_port: 1515
    match: state
    cstate: "ESTABLISHED,RELATED"
    jump: ACCEPT

# Declare Monitor Server as OSSEC server role.
ossec_is_server: yes

ssh_ip: "{{ monitor_ip|default(ansible_default_ipv4.address) }}"
adjacent_sd_ip: "{{ app_ip }}"
