---
# For setting the etc hosts entries
ip_info:
  - ip: "{{ app_ip }}"
    hostname: "{{ app_hostname }}"

### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - "securedrop-keyring_0.2.2+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
  - "securedrop-config_{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
  - "securedrop-ossec-server_3.6.0+{{ securedrop_version }}+{{ securedrop_target_distribution }}_all.deb"
  - ossec-server_3.6.0+{{ securedrop_target_distribution }}_amd64.deb

# Configure the tor onion services. The Monitor server has only one,
# for SSH, since no web interfaces.
tor_instances_v3: "{{ [{ 'service': 'sshv3', 'filename': 'mon-ssh.auth_private'}] if enable_ssh_over_tor else [] }}"

tor_auth_instances_v3:
  - "{{ 'sshv3' if enable_ssh_over_tor else [] }}"

authd_iprules:
  - chain: INPUT
    source: "{{ app_hostname  }}"
    proto: tcp
    dest_port: 1515
    match: state
    cstate: "NEW,ESTABLISHED,RELATED"
    jump: ACCEPT

  - chain: OUTPUT
    dest: "{{ app_hostname }}"
    proto: tcp
    source_port: 1515
    match: state
    cstate: "ESTABLISHED,RELATED"
    jump: ACCEPT

# Declare Monitor Server as OSSEC server role.
ossec_is_server: yes

ssh_ip: "{{ monitor_ip|default(ansible_default_ipv4.address) }}"
adjacent_sd_ip: "{{ app_ip }}"
