---
# Variables that apply to both the app and monitor server go in this file
# If the monitor or app server need different values define the variable in
# hosts_vars/app.yml or host_vars/mon.yml host_vars/development.yml
securedrop_app_code_version: "0.3.6"

tor_wait_for_hidden_services: yes
tor_hidden_services_parent_dir: "/var/lib/tor/services"
tor_user: debian-tor

disabled_kernel_modules:
  - btusb
  - bluetooth
  - iwlmvm
  - iwlwifi

ssh_2fa_dependencies:
  - libpam-google-authenticator

sysctl_flags:
  - name: "net.ipv4.tcp_max_syn_backlog"
    value: "4096"
  - name: "net.ipv4.tcp_syncookies"
    value: "1"
  - name: "net.ipv4.conf.all.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.all.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.all.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.all.secure_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.rp_filter"
    value: "1"
  - name: "net.ipv4.conf.default.accept_source_route"
    value: "0"
  - name: "net.ipv4.conf.default.accept_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.secure_redirects"
    value: "0"
  - name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: "1"
  - name: "net.ipv4.ip_forward"
    value: "0"
  - name: "net.ipv4.conf.all.send_redirects"
    value: "0"
  - name: "net.ipv4.conf.default.send_redirects"
    value: "0"
  - name: "net.ipv6.conf.all.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.default.disable_ipv6"
    value: "1"
  - name: "net.ipv6.conf.lo.disable_ipv6"
    value: "1"

ossec_group: ossec
apt_repo_url: "https://apt.freedom.press"
