---
### General (used by more than one role) ###
dns_server: "8.8.8.8"

### Used by the common role ###
ssh_users: "vagrant"

# Vagrant reserves eth0 for host gateway at 10.0.2.15; use eth1 for internal IPs.
# In production, the IPs are hardcoded, and must also be set in the firewall config.
primary_network_iface: eth1
monitor_ip: "{{ hostvars['mon-staging']['ansible_'+primary_network_iface].ipv4.address }}"
monitor_hostname: "{{ hostvars['mon-staging'].ansible_hostname }}"
app_ip: "{{ hostvars['app-staging']['ansible_'+primary_network_iface].ipv4.address }}"
app_hostname: "{{ hostvars['app-staging'].ansible_hostname }}"

### Used by the app role ###
# The app GPG public key has to be in the install_files/ansible-base/ or
# install_files/ansible-base/roles/app/files/ directory
#
# The format of the app GPG public key can be binary or ASCII-armored,
# the extension also doesn't matter
#
# The format of the app GPG fingerprint needs to be all capital letters
# and zero spaces, e.g. "B89A29DB2128160B8E4B1B4CBADDE0C7FC9F6818"
securedrop_app_gpg_public_key: "test_journalist_key.pub"
securedrop_app_gpg_fingerprint: "65A1B5FF195B56353CC63DFFCC40EF1228271441"

source_apache_log_location: "/var/log/apache2/source-error.log"
apache_logging_level: "info"

### Used by the mon role ###
# The OSSEC alert GPG public key has to be in the install_files/ansible-base/ or
# install_files/ansible-base/roles/app/files/ directory
ossec_alert_gpg_public_key: "test_admin_key.pub"
ossec_gpg_fpr: "53E1113AC1F25027BA5D475B1141E2BBB5E53711"
ossec_alert_email: "ossec@ossec.test"
smtp_relay: "smtp.faketld"
smtp_relay_port: "587"
sasl_username: "test"
sasl_domain: "ossec.test"
sasl_password: "password123"

# Disable Postfix in staging, so we don't hammer Google mail relays
# with known-bad credentials.
postfix_enable_service: no

# Permit direct access for SSH in the staging environment.
# Otherwise, all SSH connections would be forced over Tor.
ssh_listening_address: 0.0.0.0
allow_direct_access: true

### Use for backup restores ###
# If the `backup_zip` variable is defined ansible will copy the defined file to
# the app server and run the 0.3_collect.py script to unzip and restore those
# files.
# ex: backup_zip: "sd-backup-2015-01-15--21-03-32.zip"
# To use uncomment the following line and enter the correct decrypted zip
# filename between the quotes.
#backup_zip: ""

install_local_packages: true

# Don't install app-code package from the FPF apt repo, since we want to run
# the application code directly out of the local repo. Do, however, make sure
# the Apache service is configured correctly.
securedrop_app_install_from_repo: False
securedrop_app_configure_apache: True
