---
### General (used by more than one role) ###
securedrop_user: travis
securedrop_repo: "{{ lookup('env', 'TRAVIS_BUILD_DIR') }}"

### Used by the app role ###
securedrop_code: "{{ securedrop_repo }}/securedrop"

# The app gpg public key has to be in the install_files/ansible-base/ or
# install_files/ansible-base/roles/app/files/ directory
securedrop_app_gpg_public_key: "test_journalist_key.pub"
securedrop_app_gpg_fingerprint: "65A1B5FF195B56353CC63DFFCC40EF1228271441"

# Custom text on source interface
custom_notification_text: "This is an insecure SecureDrop Development server for testing ONLY. Do NOT submit documents here."
