# Roughly based off of https://mozilla.github.io/cargo-vet/configuring-ci.html

name: cargo vet

on: [push, pull_request]

jobs:
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    # Keep version in sync with rust-toolchain.toml
    container: rust:1.78.0
    env:
      CARGO_VET_VERSION: 0.9.0
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache-vet
      with:
        path: /usr/local/cargo/bin/cargo-vet
        key: cargo-vet-${{ env.CARGO_VET_VERSION }}
    - name: Install the cargo-vet binary, if needed
      if: ${{ steps.cache-vet.outputs.cache-hit != 'true' }}
      run: cargo install --version ${{ env.CARGO_VET_VERSION }} cargo-vet
    - name: Invoke cargo-vet
      run: cargo vet --locked
